version: 1
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world
pipeline-when:
  and:
    - equal:
        - << status.build.hello >>
        - success
    - equal:
        - << event.{{Event_Variable_Name_Placeholder}} >>
        - dsfbdgv