version: 1.0
pipeline-when:
  equal:
    - << event.test.test2 >>
    - Hello
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world